apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginxrs
  namespace: my-ns
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      name: my-pod-rs
      labels:
        app: my-app
    spec:
      containers:
        - name: nginxrs
          image: nginx
          ports:
            - containerPort: 8080
            
    